"""
streamlit_app.py
----------------
Interactive Streamlit interface for the AI-Based Diabetes Prediction System.

Run:
    cd backend
    pip install -r requirements.txt
    streamlit run streamlit_app.py
"""

import pandas as pd
import streamlit as st

from prediction import ModelUnavailable, load_metrics, predict
from preprocessing import PipelineUnavailable

st.set_page_config(page_title="AI-Based Diabetes Prediction System", page_icon="🩺", layout="wide")

st.title("AI-Based Diabetes Prediction System")
st.caption("Machine Learning Powered Diabetes Risk Prediction — Random Forest Classifier")

tab_predict, tab_metrics, tab_data = st.tabs(["Prediction", "Model Performance", "Dataset"])

with tab_predict:
    with st.form("patient"):
        c1, c2, c3 = st.columns(3)
        age = c1.number_input("Age (years)", 18, 120, 45)
        bmi = c2.number_input("BMI (kg/m²)", 10.0, 70.0, 27.0, step=0.1)
        activity = c3.selectbox("Physical Activity", ["Low", "Moderate", "High"])
        bp = c1.number_input("Systolic Blood Pressure (mmHg)", 70, 250, 120)
        chol = c2.number_input("Total Cholesterol (mg/dL)", 80, 500, 190)
        glucose = c3.number_input("Fasting Glucose (mg/dL)", 40, 500, 100)
        submitted = st.form_submit_button("Predict Diabetes Risk")

    if submitted:
        try:
            result = predict(
                {
                    "age": age,
                    "bmi": bmi,
                    "physical_activity": activity,
                    "blood_pressure": bp,
                    "cholesterol": chol,
                    "glucose": glucose,
                }
            )
            m1, m2, m3 = st.columns(3)
            m1.metric("Prediction", result["prediction"])
            m2.metric("Risk Probability", f"{result['risk_percentage']}%")
            m3.metric("Risk Level", result.get("risk_level", "-"))
            st.progress(min(1.0, result["probability"]))
            st.write(result["message"])
        except (ModelUnavailable, PipelineUnavailable) as exc:
            st.error(f"Model not available: {exc}")
        st.info(
            "This result is generated by a machine-learning model and is intended for "
            "educational/project purposes only. It should not be considered a medical diagnosis."
        )

with tab_metrics:
    metrics = load_metrics()
    if not metrics.get("trained"):
        st.warning("Model metrics will appear after model training.")
    else:
        cols = st.columns(5)
        for col, key, label in zip(
            cols,
            ["accuracy", "precision", "recall", "f1", "rocAuc"],
            ["Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"],
        ):
            col.metric(label, f"{metrics[key]:.3f}")
        cm = metrics["confusionMatrix"]
        st.subheader("Confusion Matrix")
        st.table(
            pd.DataFrame(
                [[cm["trueNegative"], cm["falsePositive"]], [cm["falseNegative"], cm["truePositive"]]],
                index=["Actual: Non-Diabetic", "Actual: Diabetic"],
                columns=["Predicted: Non-Diabetic", "Predicted: Diabetic"],
            )
        )
        st.subheader("ROC Curve")
        st.line_chart(pd.DataFrame(metrics["rocCurve"]).set_index("fpr"))
        st.subheader("Feature Importance")
        st.bar_chart(pd.DataFrame(metrics["featureImportance"]).set_index("feature"))

with tab_data:
    df = pd.read_csv("data/diabetes_health.csv")
    st.write(f"Records: {len(df)} — Diabetic: {int(df['diabetes'].sum())}")
    st.dataframe(df.head(100))
    st.bar_chart(df["diabetes"].value_counts().rename({0: "Non-Diabetic", 1: "Diabetic"}))
