export function SiteFooter() {
  return (
    <footer className="border-t border-border bg-surface">
      <div className="mx-auto max-w-7xl px-4 py-8 text-sm text-muted-foreground sm:px-6">
        <p className="font-medium text-foreground">AI-Based Diabetes Prediction System</p>
        <p className="mt-1 max-w-3xl">
          Academic minor project — supervised machine learning (Random Forest Classifier). Results
          are generated by a machine-learning model for educational purposes only and must not be
          treated as a medical diagnosis.
        </p>
      </div>
    </footer>
  );
}
