/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicMetricsRouteImport } from './routes/api/public/metrics'
import { Route as ApiPublicModelInfoRouteImport } from './routes/api/public/model-info'
import { Route as ApiPublicPredictRouteImport } from './routes/api/public/predict'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetricsRoute = ApiPublicMetricsRouteImport.update({
  id: '/api/public/metrics',
  path: '/api/public/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicModelInfoRoute = ApiPublicModelInfoRouteImport.update({
  id: '/api/public/model-info',
  path: '/api/public/model-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPredictRoute = ApiPublicPredictRouteImport.update({
  id: '/api/public/predict',
  path: '/api/public/predict',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/model-info': typeof ApiPublicModelInfoRoute
  '/api/public/predict': typeof ApiPublicPredictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/model-info': typeof ApiPublicModelInfoRoute
  '/api/public/predict': typeof ApiPublicPredictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/model-info': typeof ApiPublicModelInfoRoute
  '/api/public/predict': typeof ApiPublicPredictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/health'
    | '/api/public/metrics'
    | '/api/public/model-info'
    | '/api/public/predict'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/health'
    | '/api/public/metrics'
    | '/api/public/model-info'
    | '/api/public/predict'
  id:
    | '__root__'
    | '/'
    | '/api/public/health'
    | '/api/public/metrics'
    | '/api/public/model-info'
    | '/api/public/predict'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMetricsRoute: typeof ApiPublicMetricsRoute
  ApiPublicModelInfoRoute: typeof ApiPublicModelInfoRoute
  ApiPublicPredictRoute: typeof ApiPublicPredictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/metrics': {
      id: '/api/public/metrics'
      path: '/api/public/metrics'
      fullPath: '/api/public/metrics'
      preLoaderRoute: typeof ApiPublicMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/model-info': {
      id: '/api/public/model-info'
      path: '/api/public/model-info'
      fullPath: '/api/public/model-info'
      preLoaderRoute: typeof ApiPublicModelInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/predict': {
      id: '/api/public/predict'
      path: '/api/public/predict'
      fullPath: '/api/public/predict'
      preLoaderRoute: typeof ApiPublicPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMetricsRoute: ApiPublicMetricsRoute,
  ApiPublicModelInfoRoute: ApiPublicModelInfoRoute,
  ApiPublicPredictRoute: ApiPublicPredictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
